# Generated by Django 2.2 on 2021-10-02 21:14

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0014_auto_20210929_2242'),
        ('master_setups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=500)),
                ('report_html', models.TextField(blank=True, null=True)),
                ('report_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('report_type', models.CharField(max_length=50)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_on', models.DateField(blank=True, null=True)),
                ('is_generated', models.BooleanField(default=False)),
                ('generated_on', models.DateField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_by_set', to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.Country')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_by_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'report',
            },
        ),
        migrations.CreateModel(
            name='RBDReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=500)),
                ('report_html', models.TextField(blank=True, null=True)),
                ('report_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_on', models.DateField(blank=True, null=True)),
                ('is_generated', models.SmallIntegerField(default=0)),
                ('generated_on', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.Category')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rbd_confirmed_by_set', to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.Country')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rbd_generated_by_set', to=settings.AUTH_USER_MODEL)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.Month')),
                ('rbd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.RBD')),
            ],
            options={
                'verbose_name': 'RBDReport',
                'verbose_name_plural': 'RBDReports',
                'db_table': 'rbd_report',
            },
        ),
    ]
