# Generated by Django 2.2 on 2021-10-17 20:20

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_setups', '0001_initial'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RBDReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('report_type', models.CharField(choices=[('cell-summary', 'Cell Summary'), ('cell-snapshot', 'Cell Snapshot')], default='cell-summary', max_length=50)),
                ('report_html', models.TextField(blank=True, null=True)),
                ('report_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('report_csv_source', models.CharField(blank=True, max_length=500, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_on', models.DateField(blank=True, null=True)),
                ('is_generated', models.SmallIntegerField(default=0)),
                ('generated_on', models.DateField(blank=True, null=True)),
                ('log', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.Category')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rbd_confirmed_by_set', to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.Country')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rbd_generated_by_set', to=settings.AUTH_USER_MODEL)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.IndexSetup')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.Month')),
                ('rbd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.RBD')),
            ],
            options={
                'verbose_name': 'RBDReport',
                'verbose_name_plural': 'RBDReports',
                'db_table': 'rbd_report',
            },
        ),
    ]
