# Generated by Django 2.2 on 2022-01-23 21:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0026_auto_20220122_1210'),
        ('master_setups', '0007_delete_threshold'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbdreport',
            name='report_type',
            field=models.CharField(choices=[('cell-summary', 'Cell Summary'), ('cell-snapshot', 'Cell Snapshot'), ('threshold-processing', 'Threshold Processing')], default='cell-summary', max_length=50),
        ),
        migrations.CreateModel(
            name='DataLoadingReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('report_type', models.CharField(choices=[('threshold-processing', 'Threshold Processing')], default='threshold-processing', max_length=50)),
                ('report_html', models.TextField(blank=True, null=True)),
                ('report_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('report_csv_source', models.CharField(blank=True, max_length=500, null=True)),
                ('log', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.Category')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.Country')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.IndexSetup')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.Month')),
            ],
            options={
                'verbose_name': 'Data Loading Report',
                'verbose_name_plural': 'Data Loading Reports',
                'db_table': 'data_loading_report',
            },
        ),
    ]
