# Generated by Django 2.2 on 2022-01-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20220123_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbdreport',
            name='report_type',
            field=models.CharField(choices=[('cell-summary', 'Cell Summary'), ('cell-snapshot', 'Cell Snapshot')], default='cell-summary', max_length=50),
        ),
    ]
