# Generated by Django 2.2 on 2021-10-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20211002_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='rbdreport',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
