# Generated by Django 2.2 on 2022-01-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20220123_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbdreport',
            name='report_type',
            field=models.CharField(choices=[('cell-summary', 'Cell Summary'), ('cell-snapshot', 'Cell Snapshot'), ('threshold-processing', 'Threshold Processing')], default='cell-summary', max_length=50),
        ),
    ]
