# Generated by Django 2.2 on 2021-10-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_rbdreport_report_csv_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='rbdreport',
            name='report_type',
            field=models.CharField(choices=[('cell-summary', 'Cell Summary')], default='cell-summary', max_length=50),
        ),
    ]
