# Generated by Django 2.2 on 2021-10-14 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_setups', '0001_initial'),
        ('reports', '0006_rbdreport_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rbdreport',
            name='index',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='master_setups.IndexSetup'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Reports',
        ),
    ]
