# Generated by Django 2.2 on 2021-10-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20211014_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbdreport',
            name='report_type',
            field=models.CharField(choices=[('cell-summary', 'Cell Summary'), ('cell-snapshot', 'Cell Snapshot')], default='cell-summary', max_length=50),
        ),
    ]
