from django.db import models

class ProductMixin(models.Model):
    extra_1 =  models.CharField(max_length=500, null=True, blank=True)
    extra_2 =  models.CharField(max_length=500, null=True, blank=True)
    extra_3 =  models.CharField(max_length=500, null=True, blank=True)
    extra_4 =  models.CharField(max_length=500, null=True, blank=True)
    extra_5 =  models.CharField(max_length=500, null=True, blank=True)
    extra_6 =  models.CharField(max_length=500, null=True, blank=True)
    extra_7 =  models.CharField(max_length=500, null=True, blank=True)
    extra_8 =  models.CharField(max_length=500, null=True, blank=True)
    extra_9 =  models.CharField(max_length=500, null=True, blank=True)
    extra_10 =  models.CharField(max_length=500, null=True, blank=True)
    extra_11 =  models.CharField(max_length=500, null=True, blank=True)
    extra_12 =  models.CharField(max_length=500, null=True, blank=True)
    extra_13 =  models.CharField(max_length=500, null=True, blank=True)
    extra_14 =  models.CharField(max_length=500, null=True, blank=True)
    extra_15 =  models.CharField(max_length=500, null=True, blank=True)
    extra_16 =  models.CharField(max_length=500, null=True, blank=True)
    extra_17 =  models.CharField(max_length=500, null=True, blank=True)
    extra_18 =  models.CharField(max_length=500, null=True, blank=True)
    extra_19 =  models.CharField(max_length=500, null=True, blank=True)
    extra_20 =  models.CharField(max_length=500, null=True, blank=True)
    extra_21 =  models.CharField(max_length=500, null=True, blank=True)
    extra_22 =  models.CharField(max_length=500, null=True, blank=True)
    extra_23 =  models.CharField(max_length=500, null=True, blank=True)
    extra_24 =  models.CharField(max_length=500, null=True, blank=True)
    extra_25 =  models.CharField(max_length=500, null=True, blank=True)
    extra_26 =  models.CharField(max_length=500, null=True, blank=True)
    extra_27 =  models.CharField(max_length=500, null=True, blank=True)
    extra_28 =  models.CharField(max_length=500, null=True, blank=True)
    extra_29 =  models.CharField(max_length=500, null=True, blank=True)
    extra_30 =  models.CharField(max_length=500, null=True, blank=True)
    class Meta:
        abstract = True
