# Generated by Django 2.2 on 2021-09-01 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_setups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='country',
        ),
        migrations.RemoveField(
            model_name='district',
            name='province',
        ),
        migrations.RemoveField(
            model_name='player',
            name='country',
        ),
        migrations.RemoveField(
            model_name='playertag',
            name='country',
        ),
        migrations.RemoveField(
            model_name='playertag',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playertag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='province',
            name='country',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='country',
        ),
        migrations.RemoveField(
            model_name='tehsil',
            name='country',
        ),
        migrations.RemoveField(
            model_name='tehsil',
            name='district',
        ),
        migrations.DeleteModel(
            name='CityVillage',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='PlayerTag',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Tehsil',
        ),
    ]
