# Generated by Django 2.2 on 2021-06-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_setups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='audited_data_price_max',
            field=models.DecimalField(blank=True, decimal_places=2, default='10', max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='audited_data_price_min',
            field=models.DecimalField(blank=True, decimal_places=2, default='-10', max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='audited_data_purchase_max',
            field=models.DecimalField(blank=True, decimal_places=2, default='10', max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='audited_data_purchase_min',
            field=models.DecimalField(blank=True, decimal_places=2, default='-10', max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='audited_data_sales_max',
            field=models.DecimalField(blank=True, decimal_places=2, default='10', max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='audited_data_sales_min',
            field=models.DecimalField(blank=True, decimal_places=2, default='-10', max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='audited_data_stock_max',
            field=models.DecimalField(blank=True, decimal_places=2, default='10', max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='audited_data_stock_min',
            field=models.DecimalField(blank=True, decimal_places=2, default='-10', max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='outlet_factor_numaric_max',
            field=models.DecimalField(blank=True, decimal_places=2, default='1', max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='outlet_factor_numaric_min',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=11, null=True),
        ),
    ]
