# Generated by Django 2.2 on 2022-01-10 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_setups', '0002_threshold_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='threshold',
            name='audited_data_stddev_max',
            field=models.DecimalField(blank=True, decimal_places=2, default='10', max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='threshold',
            name='audited_data_stddev_min',
            field=models.DecimalField(blank=True, decimal_places=2, default='-10', max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='threshold',
            name='stddev_sample',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.Country'),
        ),
        migrations.AlterUniqueTogether(
            name='threshold',
            unique_together={('country', 'index')},
        ),
    ]
