# Generated by Django 2.2 on 2022-01-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_setups', '0003_auto_20220110_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='threshold',
            name='common_outlet_accept',
            field=models.DecimalField(blank=True, decimal_places=2, default='5', help_text='ABS (Store Actual Sales /  Store Last Month Sales - 1) <= c', max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='threshold',
            name='common_outlet_copy',
            field=models.DecimalField(blank=True, decimal_places=2, default='5', help_text='ABS (Store Actual Sales /  Store Census Sales - 1) > c', max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='threshold',
            name='drop_outlet_copied',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='threshold',
            name='drop_outlet_copied_once',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='threshold',
            name='new_outlet_accept_a',
            field=models.DecimalField(blank=True, decimal_places=2, default='5', help_text='ABS (Store Actual Sales /  Store Census Sales - 1) <= a', max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='threshold',
            name='new_outlet_accept_b',
            field=models.DecimalField(blank=True, decimal_places=2, default='5', help_text='ABS (Store Actual Sales /  Avg Cell Sales - 1) <= b', max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='threshold',
            name='new_outlet_drop_a',
            field=models.DecimalField(blank=True, decimal_places=2, default='5', help_text='ABS (Store Actual Sales /  Store Census Sales - 1) > a', max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='threshold',
            name='new_outlet_drop_b',
            field=models.DecimalField(blank=True, decimal_places=2, default='5', help_text='ABS (Store Actual Sales /  Avg Cell Sales - 1) > b', max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='threshold',
            name='weighted_cell',
            field=models.DecimalField(blank=True, decimal_places=2, default='80', max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='threshold',
            name='weighted_store',
            field=models.DecimalField(blank=True, decimal_places=2, default='80', max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='audited_data_price_max',
            field=models.DecimalField(blank=True, decimal_places=2, default='10', help_text='Apply Last Month Price Cleaning on the Stores + P_Codes', max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='audited_data_stddev_max',
            field=models.DecimalField(blank=True, decimal_places=2, default='3', help_text='(Store + P_code Actual Sales) Shall lie in between Avg (P_code Sales) +/- 3 SD ', max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='audited_data_stddev_min',
            field=models.DecimalField(blank=True, decimal_places=2, default='-3', max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='outlet_factor_numaric_max',
            field=models.DecimalField(blank=True, decimal_places=2, default='1', help_text='love', max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='stddev_sample',
            field=models.BooleanField(default=True, help_text='Use StdDev Sample if enable else StdDev Population'),
        ),
    ]
