# Generated by Django 2.2 on 2022-01-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_setups', '0004_auto_20220110_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='outlet_factor_numaric_max',
            field=models.DecimalField(blank=True, decimal_places=2, default='1', max_digits=11, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='threshold',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='threshold',
            name='index',
        ),
    ]
