# Generated by Django 2.2 on 2022-01-11 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_setups', '0005_auto_20220111_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='threshold',
            name='index',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='master_setups.IndexSetup'),
            preserve_default=False,
        ),
    ]
