# Generated by Django 2.2 on 2022-01-11 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_setups', '0006_threshold_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Threshold',
        ),
    ]
