# Generated by Django 2.2 on 2022-02-03 23:16

import core.mixinsModels
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('master_setups', '0007_delete_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexsetup',
            name='code',
            field=core.mixinsModels.UpperCaseCharField(db_index=True, max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')]),
        ),
        migrations.AlterField(
            model_name='indexsetup',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
