# Generated by Django 2.2 on 2021-10-17 20:20

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_setups', '0001_initial'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usableoutlet',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.Country'),
        ),
        migrations.AddField(
            model_name='usableoutlet',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.IndexSetup'),
        ),
        migrations.AddField(
            model_name='usableoutlet',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.Month'),
        ),
        migrations.AddField(
            model_name='usableoutlet',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.Outlet'),
        ),
        migrations.AddField(
            model_name='usableoutlet',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.Upload'),
        ),
        migrations.AddField(
            model_name='upload',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_setups.Country'),
        ),
        migrations.AddField(
            model_name='upload',
            name='index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_setups.IndexSetup'),
        ),
        migrations.AddField(
            model_name='tehsil',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.Country'),
        ),
        migrations.AddField(
            model_name='tehsil',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.District'),
        ),
        migrations.AddField(
            model_name='regiontype',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.Country'),
        ),
        migrations.AddField(
            model_name='region',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.Country'),
        ),
        migrations.AddField(
            model_name='region',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='master_data.Region'),
        ),
        migrations.AddField(
            model_name='region',
            name='region_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.RegionType'),
        ),
        migrations.AddField(
            model_name='region',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.Upload'),
        ),
        migrations.AddField(
            model_name='rbd',
            name='cell',
            field=models.ManyToManyField(to='master_data.Cell'),
        ),
        migrations.AddField(
            model_name='rbd',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.Country'),
        ),
        migrations.AddField(
            model_name='rbd',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.IndexSetup'),
        ),
        migrations.AddField(
            model_name='province',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.Country'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.Country'),
        ),
        migrations.AddField(
            model_name='product',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.Upload'),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='city_village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.CityVillage'),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.Country'),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.IndexSetup'),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.Month'),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.Outlet'),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='outlet_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.OutletStatus'),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='outlet_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.OutletType'),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.Upload'),
        ),
        migrations.AddField(
            model_name='outlettype',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.Country'),
        ),
        migrations.AddField(
            model_name='outlettype',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='master_data.OutletType'),
        ),
        migrations.AddField(
            model_name='outlettype',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.Upload'),
        ),
        migrations.AddField(
            model_name='outletstatus',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.Country'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.Country'),
        ),
        migrations.AddField(
            model_name='month',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.Country'),
        ),
        migrations.AddField(
            model_name='indexcategory',
            name='category',
            field=models.ManyToManyField(related_name='index_category', to='master_data.Category'),
        ),
        migrations.AddField(
            model_name='indexcategory',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.Country'),
        ),
        migrations.AddField(
            model_name='indexcategory',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.IndexSetup'),
        ),
        migrations.AddField(
            model_name='district',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.Country'),
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.Province'),
        ),
        migrations.AddField(
            model_name='collabel',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.Country'),
        ),
        migrations.AddField(
            model_name='cityvillage',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.Country'),
        ),
        migrations.AddField(
            model_name='cityvillage',
            name='tehsil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.Tehsil'),
        ),
        migrations.AddField(
            model_name='cityvillage',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.Upload'),
        ),
        migrations.AddField(
            model_name='census',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.Country'),
        ),
        migrations.AddField(
            model_name='census',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.Upload'),
        ),
        migrations.AddField(
            model_name='cellmonthacv',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.Cell'),
        ),
        migrations.AddField(
            model_name='cellmonthacv',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.Country'),
        ),
        migrations.AddField(
            model_name='cellmonthacv',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.IndexSetup'),
        ),
        migrations.AddField(
            model_name='cellmonthacv',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.Month'),
        ),
        migrations.AddField(
            model_name='cell',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.Country'),
        ),
        migrations.AddField(
            model_name='cell',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.IndexSetup'),
        ),
        migrations.AddField(
            model_name='cell',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.Upload'),
        ),
        migrations.AddField(
            model_name='category',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.Country'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='master_data.Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.Upload'),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.Category'),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.Country'),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.Month'),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.Outlet'),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.Product'),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.Upload'),
        ),
        migrations.AlterUniqueTogether(
            name='usableoutlet',
            unique_together={('country', 'month', 'index', 'outlet', 'cell')},
        ),
        migrations.AlterUniqueTogether(
            name='tehsil',
            unique_together={('country', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='regiontype',
            unique_together={('country', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('country', 'code', 'parent')},
        ),
        migrations.AlterUniqueTogether(
            name='rbd',
            unique_together={('country', 'name', 'index')},
        ),
        migrations.AlterUniqueTogether(
            name='province',
            unique_together={('country', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('country', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='panelprofile',
            unique_together={('country', 'outlet', 'month', 'index')},
        ),
        migrations.AlterUniqueTogether(
            name='outlettype',
            unique_together={('country', 'parent', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='outletstatus',
            unique_together={('country', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='outlet',
            unique_together={('country', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='month',
            unique_together={('country', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('country', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='collabel',
            unique_together={('country', 'model_name', 'col_name')},
        ),
        migrations.AlterUniqueTogether(
            name='cityvillage',
            unique_together={('country', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='cellmonthacv',
            unique_together={('country', 'month', 'cell', 'index')},
        ),
        migrations.AlterUniqueTogether(
            name='cell',
            unique_together={('country', 'name', 'index')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('country', 'parent', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='auditdata',
            unique_together={('country', 'outlet', 'product', 'month')},
        ),
    ]
