# Generated by Django 2.2 on 2021-06-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_auto_20210612_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productaudit',
            name='sales_projected_units',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productaudit',
            name='sales_projected_value',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productaudit',
            name='sales_projected_volume',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productaudit',
            name='sales_unprojected_units',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productaudit',
            name='sales_unprojected_value',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productaudit',
            name='sales_unprojected_volume',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
