# Generated by Django 2.2 on 2021-10-18 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_auto_20211017_2020'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auditdata',
            table='audit_data',
        ),
    ]
