# Generated by Django 2.2 on 2021-09-01 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_setups', '0002_auto_20210901_2130'),
        ('master_data', '0003_auto_20210901_2130'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cityvillage',
            unique_together={('country', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('country', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='province',
            unique_together={('country', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='tehsil',
            unique_together={('country', 'code')},
        ),
    ]
