# Generated by Django 2.2 on 2021-09-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_auto_20210915_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelprofile',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
