# Generated by Django 2.2 on 2021-09-06 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_setups', '0001_initial'),
        ('master_data', '0003_collabel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collabel',
            unique_together={('country', 'model_name', 'col_name')},
        ),
    ]
