# Generated by Django 2.2 on 2021-09-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_auto_20210906_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collabel',
            name='model_name',
            field=models.CharField(max_length=150),
        ),
    ]
