# Generated by Django 2.2 on 2021-09-01 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_auto_20210901_2245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tehsil',
            options={'select_on_save': True, 'verbose_name': 'Tehsil', 'verbose_name_plural': 'Tehsils'},
        ),
    ]
