# Generated by Django 2.2 on 2021-06-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_auto_20210612_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='month',
            options={'ordering': ['month', 'year'], 'verbose_name': 'Mont', 'verbose_name_plural': 'Months'},
        ),
        migrations.RenameField(
            model_name='month',
            old_name='is_lock',
            new_name='is_locked',
        ),
        migrations.AlterField(
            model_name='month',
            name='name',
            field=models.CharField(choices=[('JANUARY', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('APRIL', 'Aapril'), ('MAY', 'May'), ('JUNE', 'June'), ('JULY', 'July'), ('AUGUST', 'August'), ('SEPTEMBER', 'September'), ('OCTOBER', 'October'), ('NOVEMBER', 'November'), ('DECEMBER', 'December')], max_length=150),
        ),
    ]
