# Generated by Django 2.2 on 2021-09-15 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_panelprofile_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='country1',
            new_name='country_of_origin',
        ),
    ]
