# Generated by Django 2.2 on 2022-01-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_auto_20220107_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdatachild',
            name='avg_sales',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='auditdatachild',
            name='sd_range_max',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='auditdatachild',
            name='sd_range_min',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='auditdatachild',
            name='sd_sales',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True),
        ),
    ]
