# Generated by Django 2.2 on 2021-09-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_auto_20210906_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collabel',
            name='code',
        ),
        migrations.RemoveField(
            model_name='collabel',
            name='name',
        ),
    ]
