# Generated by Django 2.2 on 2021-09-02 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_auto_20210901_2343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tehsil',
            options={'verbose_name': 'Tehsil', 'verbose_name_plural': 'Tehsils'},
        ),
    ]
