# Generated by Django 2.2 on 2021-06-18 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_auto_20210618_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='month',
            old_name='is_last_month',
            new_name='is_current_month',
        ),
    ]
