# Generated by Django 2.2 on 2022-01-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_auto_20220110_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdatachild',
            name='flag_copied_previous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditdatachild',
            name='flag_neg_sales_corr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditdatachild',
            name='flag_outlier',
            field=models.BooleanField(default=False),
        ),
    ]
