# Generated by Django 2.2 on 2021-09-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_auto_20210906_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityvillage',
            name='extra_21',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cityvillage',
            name='extra_22',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cityvillage',
            name='extra_23',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cityvillage',
            name='extra_24',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cityvillage',
            name='extra_25',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cityvillage',
            name='extra_26',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cityvillage',
            name='extra_27',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cityvillage',
            name='extra_28',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cityvillage',
            name='extra_29',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cityvillage',
            name='extra_30',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
