# Generated by Django 2.2 on 2021-06-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_auto_20210618_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='name',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('Aapril', 'Aapril'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=150),
        ),
    ]
