# Generated by Django 2.2 on 2021-09-02 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_setups', '0002_auto_20210901_2130'),
        ('master_data', '0006_auto_20210902_0031'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('country', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('country', 'name')},
        ),
    ]
