# Generated by Django 2.2 on 2022-01-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_auto_20220110_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdatachild',
            name='flag_price',
            field=models.BooleanField(default=False),
        ),
    ]
