# Generated by Django 2.2 on 2021-09-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_auto_20210915_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productaudit',
            name='appreciation_award',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='avaibility',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='cash_discount',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='facing_empty',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='facing_not_empty',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='forward',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='gift_with_purchase',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='no_of_pack_without_graphic_health_warning_facing',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='no_of_pack_without_graphic_health_warning_total_stock',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='no_of_pack_without_none_tax_stamp',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='other_trade_promotion',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='pack_without_graphic_health_warning',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='point_of_sales_counter_shield',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='point_of_sales_counter_top_display',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='point_of_sales_lighter',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='point_of_sales_none',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='point_of_sales_others',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='point_of_sales_poster',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='point_of_sales_price_sticker',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='point_of_sales_signboard',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='point_of_sales_umbrella',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='price_in_pack',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='price_in_unit',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='priceother',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='product_details',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='product_foc',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='purchasediary',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='purchaseinvoice',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='purchaseother1',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='purchaseother2',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='reserve',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='sales_projected_units',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='sales_projected_value',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='sales_projected_volume',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='sales_unprojected_units',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='sales_unprojected_value',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='sales_unprojected_volume',
        ),
        migrations.RemoveField(
            model_name='productaudit',
            name='total_none_empty_facing_forward_reserve',
        ),
        migrations.AddField(
            model_name='productaudit',
            name='audit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productaudit',
            name='opening_stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='productaudit',
            name='price',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productaudit',
            name='purchase_1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='productaudit',
            name='purchase_2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='productaudit',
            name='purchase_3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='productaudit',
            name='purchase_4',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='productaudit',
            name='purchase_5',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='productaudit',
            name='rev_purchase',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='productaudit',
            name='sales',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productaudit',
            name='sales_val',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='productaudit',
            name='sales_vol',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='productaudit',
            name='stock_1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='productaudit',
            name='stock_2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='productaudit',
            name='stock_3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='productaudit',
            name='total_purchase',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='productaudit',
            name='total_stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='productaudit',
            name='vd_factor',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productaudit',
            name='week',
            field=models.IntegerField(default=0),
        ),
    ]
