# Generated by Django 2.2 on 2021-09-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_auto_20210915_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productaudit',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='productaudit',
            name='sales',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='productaudit',
            name='vd_factor',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
    ]
