# Generated by Django 2.2 on 2021-09-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_auto_20210902_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityvillage',
            name='player_tag',
        ),
        migrations.AddField(
            model_name='cityvillage',
            name='player',
            field=models.ManyToManyField(to='master_data.Player'),
        ),
        migrations.AddField(
            model_name='cityvillage',
            name='tag',
            field=models.ManyToManyField(to='master_data.Tag'),
        ),
        migrations.DeleteModel(
            name='PlayerTag',
        ),
    ]
