# Generated by Django 2.2 on 2022-01-11 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_setups', '0007_delete_threshold'),
        ('master_data', '0007_auditdatachild_flag_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('audited_data_purchase_min', models.DecimalField(blank=True, decimal_places=2, default='-10', max_digits=11, null=True)),
                ('audited_data_purchase_max', models.DecimalField(blank=True, decimal_places=2, default='10', max_digits=11, null=True)),
                ('audited_data_sales_min', models.DecimalField(blank=True, decimal_places=2, default='-10', max_digits=11, null=True)),
                ('audited_data_sales_max', models.DecimalField(blank=True, decimal_places=2, default='10', max_digits=11, null=True)),
                ('audited_data_stock_min', models.DecimalField(blank=True, decimal_places=2, default='-10', max_digits=11, null=True)),
                ('audited_data_stock_max', models.DecimalField(blank=True, decimal_places=2, default='10', max_digits=11, null=True)),
                ('audited_data_price_min', models.DecimalField(blank=True, decimal_places=2, default='-10', max_digits=11, null=True)),
                ('audited_data_price_max', models.DecimalField(blank=True, decimal_places=2, default='10', help_text='Apply Last Month Price Cleaning on the Stores + P_Codes', max_digits=11, null=True)),
                ('audited_data_stddev_min', models.DecimalField(blank=True, decimal_places=2, default='-3', max_digits=11, null=True)),
                ('audited_data_stddev_max', models.DecimalField(blank=True, decimal_places=2, default='3', help_text='(Store + P_code Actual Sales) Shall lie in between Avg (P_code Sales) +/- 3 SD ', max_digits=11, null=True)),
                ('stddev_sample', models.BooleanField(default=True, help_text='Use StdDev Sample if enable else StdDev Population')),
                ('outlet_factor_numaric_min', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=11, null=True)),
                ('outlet_factor_numaric_max', models.DecimalField(blank=True, decimal_places=2, default='1', max_digits=11, null=True)),
                ('common_outlet_accept', models.DecimalField(blank=True, decimal_places=2, default='5', help_text='ABS (Store Actual Sales /  Store Last Month Sales - 1) <= c', max_digits=11, null=True)),
                ('common_outlet_copy', models.DecimalField(blank=True, decimal_places=2, default='5', help_text='ABS (Store Actual Sales /  Store Census Sales - 1) > c', max_digits=11, null=True)),
                ('new_outlet_accept_a', models.DecimalField(blank=True, decimal_places=2, default='5', help_text='ABS (Store Actual Sales /  Store Census Sales - 1) <= a', max_digits=11, null=True)),
                ('new_outlet_drop_a', models.DecimalField(blank=True, decimal_places=2, default='5', help_text='ABS (Store Actual Sales /  Store Census Sales - 1) > a', max_digits=11, null=True)),
                ('new_outlet_accept_b', models.DecimalField(blank=True, decimal_places=2, default='5', help_text='ABS (Store Actual Sales /  Avg Cell Sales - 1) <= b', max_digits=11, null=True)),
                ('new_outlet_drop_b', models.DecimalField(blank=True, decimal_places=2, default='5', help_text='ABS (Store Actual Sales /  Avg Cell Sales - 1) > b', max_digits=11, null=True)),
                ('drop_outlet_copied', models.BooleanField(default=True)),
                ('drop_outlet_copied_once', models.BooleanField(default=True)),
                ('weighted_store', models.DecimalField(blank=True, decimal_places=2, default='80', max_digits=11, null=True)),
                ('weighted_cell', models.DecimalField(blank=True, decimal_places=2, default='80', max_digits=11, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.Category')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.Country')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.IndexSetup')),
            ],
            options={
                'verbose_name': 'Threshold',
                'verbose_name_plural': 'Thresholds',
                'db_table': 'threshold',
            },
        ),
    ]
