# Generated by Django 2.2 on 2021-09-09 21:48

import core.mixinsModels
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('master_setups', '0001_initial'),
        ('master_data', '0007_auto_20210906_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutletStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', core.mixinsModels.UpperCaseCharField(max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')])),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.Country')),
            ],
            options={
                'verbose_name': 'OutletStatus',
                'verbose_name_plural': 'OutletStatuses',
                'db_table': 'outlet_status',
                'unique_together': {('country', 'code')},
            },
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='acv',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='city_village',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_data.CityVillage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='nra_tagging',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='ra_tagging',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='ret_tagging',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='rex_tagging',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='tts_tagging',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='wave',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='panelprofile',
            name='outlet_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_data.OutletStatus'),
            preserve_default=False,
        ),
    ]
