# Generated by Django 2.2 on 2021-06-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_auto_20210618_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='cell_acv',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cell',
            name='num_universe',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cell',
            name='optimal_panel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='panelprofile',
            name='num_factor',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='panelprofile',
            name='wtd_factor',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_per_stick',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='productaudit',
            name='cash_discount',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name='productaudit',
            name='price_in_pack',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name='productaudit',
            name='price_in_unit',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name='productaudit',
            name='priceother',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name='productaudit',
            name='sales_projected_units',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='productaudit',
            name='sales_projected_value',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='productaudit',
            name='sales_projected_volume',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='productaudit',
            name='sales_unprojected_units',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='productaudit',
            name='sales_unprojected_value',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='productaudit',
            name='sales_unprojected_volume',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
    ]
