# Generated by Django 2.2 on 2021-09-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0008_auto_20210902_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityvillage',
            name='player',
        ),
        migrations.RemoveField(
            model_name='cityvillage',
            name='tag',
        ),
        migrations.CreateModel(
            name='PlayerTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('player', models.ManyToManyField(to='master_data.Player')),
                ('tag', models.ManyToManyField(to='master_data.Tag')),
            ],
            options={
                'verbose_name': 'PlayerTag',
                'verbose_name_plural': 'PlayerTags',
                'db_table': 'player_tag',
            },
        ),
        migrations.AddField(
            model_name='cityvillage',
            name='player_tag',
            field=models.ManyToManyField(to='master_data.PlayerTag'),
        ),
    ]
