# Generated by Django 2.2 on 2021-06-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0008_auto_20210620_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelprofile',
            name='turnover',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='panelprofile',
            name='num_factor',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='panelprofile',
            name='wtd_factor',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
    ]
