# Generated by Django 2.2 on 2021-09-15 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0008_auto_20210915_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productaudit',
            name='week',
        ),
    ]
