# Generated by Django 2.2 on 2022-01-12 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_setups', '0007_delete_threshold'),
        ('master_data', '0008_threshold'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='threshold',
            unique_together={('country', 'index', 'category')},
        ),
    ]
