# Generated by Django 2.2 on 2021-09-02 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_auto_20210902_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityvillage',
            name='player_tag',
        ),
        migrations.AddField(
            model_name='cityvillage',
            name='player_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.PlayerTag'),
        ),
    ]
