# Generated by Django 2.2 on 2021-06-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_auto_20210620_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='usableoutlet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='import_mode',
            field=models.CharField(choices=[('APPEND', 'Append: Add records in the table.'), ('UPDATE', 'Update: If records exist update.'), ('APPENDUPDATE', 'Append/Update: If  records exist update otherwise add.'), ('REFRESH', 'Reresh: Delete all records and repopulate from the source.')], max_length=20),
        ),
    ]
