# Generated by Django 2.2 on 2021-09-19 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_setups', '0001_initial'),
        ('master_data', '0009_remove_productaudit_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='cell_acv',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='cell',
            name='num_universe',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='cellstructure',
            name='cell_acv',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='cellstructure',
            name='num_universe',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='panelprofile',
            name='acv',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='panelprofile',
            name='num_factor',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='panelprofile',
            name='turnover',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='panelprofile',
            name='wtd_factor',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='productaudit',
            name='price',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='productaudit',
            name='sales',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='productaudit',
            name='sales_val',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='productaudit',
            name='sales_vol',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='productaudit',
            name='vd_factor',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.CreateModel(
            name='CellMonthACV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('cell_acv', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.Cell')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setups.Country')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.Month')),
            ],
            options={
                'verbose_name': 'CellMonthACV',
                'verbose_name_plural': 'CellMonthACVs',
                'db_table': 'cell_month_acv',
                'unique_together': {('country', 'month')},
            },
        ),
    ]
