# Generated by Django 2.2 on 2022-01-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_auto_20220112_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threshold',
            old_name='audited_data_stddev_max',
            new_name='audited_data_stddev',
        ),
        migrations.RemoveField(
            model_name='threshold',
            name='audited_data_stddev_min',
        ),
    ]
