# Generated by Django 2.2 on 2021-09-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_auto_20210909_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
