# Generated by Django 2.2 on 2021-09-10 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0010_auto_20210910_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panelprofile',
            name='wave',
        ),
    ]
