# Generated by Django 2.2 on 2022-01-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0010_auto_20220113_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditdatachild',
            old_name='sd_range_max',
            new_name='sd_purchase_range_max',
        ),
        migrations.RenameField(
            model_name='auditdatachild',
            old_name='sd_range_min',
            new_name='sd_purchase_range_min',
        ),
        migrations.AddField(
            model_name='auditdatachild',
            name='valid_purchase_max',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='auditdatachild',
            name='valid_purchase_min',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='auditdatachild',
            name='valid_sales_max',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='auditdatachild',
            name='valid_sales_min',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True),
        ),
    ]
