# Generated by Django 2.2 on 2021-09-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_setups', '0001_initial'),
        ('master_data', '0010_auto_20210919_0928'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cellmonthacv',
            unique_together={('country', 'month', 'cell')},
        ),
    ]
