# Generated by Django 2.2 on 2022-01-13 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0011_auto_20220113_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditdatachild',
            name='sd_purchase_range_max',
        ),
        migrations.RemoveField(
            model_name='auditdatachild',
            name='sd_purchase_range_min',
        ),
    ]
