# Generated by Django 2.2 on 2021-09-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0011_remove_panelprofile_wave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelprofile',
            name='nra_tagging',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='panelprofile',
            name='ra_tagging',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='panelprofile',
            name='ret_tagging',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='panelprofile',
            name='rex_tagging',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='panelprofile',
            name='tts_tagging',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=15, null=True),
        ),
    ]
