# Generated by Django 2.2 on 2021-09-02 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_setups', '0002_auto_20210901_2130'),
        ('master_data', '0011_auto_20210902_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertag',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_setups.Country'),
            preserve_default=False,
        ),
    ]
