# Generated by Django 2.2 on 2021-07-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0011_auto_20210624_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='rbd',
            name='cell_acv',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='rbd',
            name='num_universe',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
    ]
