# Generated by Django 2.2 on 2022-01-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0012_auto_20220113_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='threshold',
            name='drop_store_copy_once_drop_status_code',
            field=models.CharField(default='0,0', help_text='Copy Once Dropped NC / PC  Stores - if Store is weighted Store in the MBD', max_length=250),
        ),
    ]
