# Generated by Django 2.2 on 2021-09-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0012_auto_20210910_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelprofile',
            name='nra_tagging',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='panelprofile',
            name='ra_tagging',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='panelprofile',
            name='ret_tagging',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='panelprofile',
            name='rex_tagging',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='panelprofile',
            name='tts_tagging',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
