# Generated by Django 2.2 on 2021-09-02 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_setups', '0002_auto_20210901_2130'),
        ('master_data', '0012_playertag_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertag',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_data.Player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playertag',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_data.Tag'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='playertag',
            unique_together={('country', 'player', 'tag')},
        ),
        migrations.RemoveField(
            model_name='playertag',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playertag',
            name='tag',
        ),
    ]
