# Generated by Django 2.2 on 2021-07-02 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0012_auto_20210702_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rbd',
            old_name='cell_acv',
            new_name='acv',
        ),
    ]
