# Generated by Django 2.2 on 2021-09-02 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0013_auto_20210902_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertag',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_data.Player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playertag',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_data.Tag'),
            preserve_default=False,
        ),
    ]
