# Generated by Django 2.2 on 2021-09-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0013_auto_20210926_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelprofile',
            name='audit_status',
            field=models.CharField(choices=[('A', 'Audited'), ('C', 'Copied'), ('E', 'Estimated')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='productaudit',
            name='audit_status',
            field=models.CharField(choices=[('A', 'Audited'), ('C', 'Copied'), ('E', 'Estimated')], default='A', max_length=1),
        ),
    ]
