# Generated by Django 2.2 on 2021-07-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0013_auto_20210702_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='rbd',
            name='optimal_panel',
            field=models.IntegerField(default=0),
        ),
    ]
