# Generated by Django 2.2 on 2021-07-02 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0014_rbd_optimal_panel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rbd',
            old_name='acv',
            new_name='cell_acv',
        ),
    ]
