# Generated by Django 2.2 on 2021-10-05 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0014_auto_20210929_2242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CellStructure',
        ),
    ]
