# Generated by Django 2.2 on 2022-01-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0015_auto_20220114_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelprofile',
            name='common_outlet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='copied_outlet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='droped_outlet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='new_outlet',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='price_variation',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='panelprofilechild',
            name='common_outlet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='panelprofilechild',
            name='copied_outlet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='panelprofilechild',
            name='droped_outlet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='panelprofilechild',
            name='new_outlet',
            field=models.BooleanField(default=True),
        ),
    ]
