# Generated by Django 2.2 on 2021-10-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0015_delete_cellstructure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collabel',
            name='model_name',
            field=models.CharField(choices=[('CityVillage', 'CityVillage'), ('Product', 'Product')], default='CityVillage', max_length=150),
        ),
    ]
