# Generated by Django 2.2 on 2021-09-12 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0016_auto_20210910_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panelprofile',
            name='region',
        ),
    ]
