# Generated by Django 2.2 on 2021-10-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0016_auto_20211005_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityvillage',
            name='extra_100',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
