# Generated by Django 2.2 on 2021-10-06 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0017_cityvillage_extra_100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityvillage',
            name='extra_100',
        ),
    ]
