# Generated by Django 2.2 on 2022-01-14 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_setups', '0007_delete_threshold'),
        ('master_data', '0017_auto_20220114_0726'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usableoutlet',
            unique_together={('country', 'month', 'index', 'outlet')},
        ),
        migrations.RemoveField(
            model_name='usableoutlet',
            name='cell',
        ),
    ]
