# Generated by Django 2.2 on 2021-09-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0017_remove_panelprofile_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelprofile',
            name='cell_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='lms',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
