# Generated by Django 2.2 on 2021-09-13 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_setups', '0001_initial'),
        ('master_data', '0018_auto_20210913_0938'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cell',
            unique_together={('country', 'name')},
        ),
    ]
