# Generated by Django 2.2 on 2021-10-12 20:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_setups', '0001_initial'),
        ('master_data', '0018_remove_cityvillage_extra_100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexcategory',
            old_name='index_setup',
            new_name='index',
        ),
        migrations.AddField(
            model_name='cell',
            name='index',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_setups.IndexSetup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='extra_1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='extra_10',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='extra_11',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='extra_12',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='extra_13',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='extra_14',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='extra_15',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='extra_16',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='extra_17',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='extra_18',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='extra_19',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='extra_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='extra_20',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='extra_21',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='extra_22',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='extra_23',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='extra_24',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='extra_25',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='extra_26',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='extra_27',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='extra_28',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='extra_29',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='extra_3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='extra_30',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='extra_4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='extra_5',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='extra_6',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='extra_7',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='extra_8',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='panelprofile',
            name='extra_9',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_setups.IndexSetup'),
        ),
        migrations.AddField(
            model_name='upload',
            name='other',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collabel',
            name='model_name',
            field=models.CharField(choices=[('CityVillage', 'CityVillage'), ('Product', 'Product'), ('PanelProfile', 'PanelProfile')], default='CityVillage', max_length=150),
        ),
    ]
