# Generated by Django 2.2 on 2021-09-13 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0019_auto_20210913_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='code',
        ),
    ]
