# Generated by Django 2.2 on 2021-10-14 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_setups', '0001_initial'),
        ('master_data', '0019_auto_20211012_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellmonthacv',
            name='index',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='master_setups.IndexSetup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rbd',
            name='index',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='master_setups.IndexSetup'),
            preserve_default=False,
        ),
    ]
