# Generated by Django 2.2 on 2022-01-17 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_setups', '0007_delete_threshold'),
        ('master_data', '0019_auto_20220117_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='usableoutlet',
            name='cell',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_data.Cell'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usableoutlet',
            name='status',
            field=models.CharField(choices=[('USABLE', 'Usable'), ('NOTUSABLE', 'Not Usable'), ('DROP', 'Drop'), ('QUARANTINE', 'Quarantine')], default='USABLE', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='usableoutlet',
            unique_together={('country', 'month', 'index', 'outlet', 'cell')},
        ),
    ]
