# Generated by Django 2.2 on 2021-10-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0020_auto_20211014_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexcategory',
            name='category',
            field=models.ManyToManyField(related_name='index_category', to='master_data.Category'),
        ),
    ]
