# Generated by Django 2.2 on 2021-09-13 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_setups', '0001_initial'),
        ('master_data', '0020_remove_cell_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rbd',
            unique_together={('country', 'name')},
        ),
        migrations.RemoveField(
            model_name='rbd',
            name='code',
        ),
    ]
