# Generated by Django 2.2 on 2022-01-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_setups', '0007_delete_threshold'),
        ('master_data', '0020_auto_20220117_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletcensus',
            name='category_sales_avg',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='outletcensus',
            name='category_sales_from',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='outletcensus',
            name='category_sales_to',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='outletcensus',
            name='insert_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='outletcensus',
            name='over_all_sales_avg',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='outletcensus',
            name='over_all_sales_from',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='outletcensus',
            name='over_all_sales_to',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='outletcensus',
            unique_together={('country', 'outlet', 'category')},
        ),
        migrations.RemoveField(
            model_name='outletcensus',
            name='index',
        ),
        migrations.RemoveField(
            model_name='outletcensus',
            name='month',
        ),
        migrations.RemoveField(
            model_name='outletcensus',
            name='sales',
        ),
    ]
