# Generated by Django 2.2 on 2021-10-14 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0021_auto_20211014_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='index',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='master_setups.IndexSetup'),
            preserve_default=False,
        ),
    ]
