# Generated by Django 2.2 on 2021-09-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0021_auto_20210913_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='condition_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
