# Generated by Django 2.2 on 2022-01-17 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0021_auto_20220117_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outletcensus',
            name='insert_date',
        ),
    ]
