# Generated by Django 2.2 on 2021-09-14 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0022_cell_condition_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.Upload'),
        ),
    ]
