# Generated by Django 2.2 on 2021-10-15 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0022_auto_20211014_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_setups.Country'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_setups.IndexSetup'),
        ),
    ]
