# Generated by Django 2.2 on 2022-01-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0022_remove_outletcensus_insert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletcensus',
            name='category_sales_avg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='outletcensus',
            name='over_all_sales_avg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
