# Generated by Django 2.2 on 2022-01-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0023_auto_20220119_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletcensus',
            name='category_sales_from',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='outletcensus',
            name='category_sales_to',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='outletcensus',
            name='over_all_sales_from',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='outletcensus',
            name='over_all_sales_to',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
