# Generated by Django 2.2 on 2022-01-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0024_auto_20220119_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='ipp',
            field=models.BooleanField(default=False),
        ),
    ]
