# Generated by Django 2.2 on 2021-10-15 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0025_auto_20211015_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.Upload'),
        ),
        migrations.AlterField(
            model_name='cell',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.Upload'),
        ),
        migrations.AlterField(
            model_name='census',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.Upload'),
        ),
        migrations.AlterField(
            model_name='cityvillage',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.Upload'),
        ),
        migrations.AlterField(
            model_name='outlettype',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.Upload'),
        ),
        migrations.AlterField(
            model_name='panelprofile',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.Upload'),
        ),
        migrations.AlterField(
            model_name='product',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.Upload'),
        ),
        migrations.AlterField(
            model_name='productaudit',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.Upload'),
        ),
        migrations.AlterField(
            model_name='region',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.Upload'),
        ),
        migrations.AlterField(
            model_name='usableoutlet',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_data.Upload'),
        ),
    ]
