# Generated by Django 2.2 on 2022-01-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0025_cell_ipp'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdata',
            name='purchase',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='auditdatachild',
            name='purchase',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
