# Generated by Django 2.2 on 2022-01-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0026_auto_20220122_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdata',
            name='flag_purchse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='flag_sales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditdata',
            name='flag_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditdatachild',
            name='flag_purchse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditdatachild',
            name='flag_sales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditdatachild',
            name='flag_stock',
            field=models.BooleanField(default=False),
        ),
    ]
