# Generated by Django 2.2 on 2022-01-24 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0027_auto_20220124_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threshold',
            name='outlet_factor_numaric_max',
        ),
        migrations.RemoveField(
            model_name='threshold',
            name='outlet_factor_numaric_min',
        ),
    ]
