# Generated by Django 2.2 on 2021-10-16 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_setups', '0001_initial'),
        ('master_data', '0028_auto_20211015_1236'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cell',
            unique_together={('country', 'name', 'index')},
        ),
        migrations.AlterUniqueTogether(
            name='cellmonthacv',
            unique_together={('country', 'month', 'cell', 'index')},
        ),
        migrations.AlterUniqueTogether(
            name='panelprofile',
            unique_together={('country', 'outlet', 'month', 'index')},
        ),
        migrations.AlterUniqueTogether(
            name='rbd',
            unique_together={('country', 'name', 'index')},
        ),
    ]
