# Generated by Django 2.2 on 2022-01-28 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_setups', '0007_delete_threshold'),
        ('master_data', '0029_auto_20220128_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='usableoutlet',
            name='category',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='master_data.Category'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='usableoutlet',
            unique_together={('country', 'month', 'index', 'category', 'outlet', 'cell')},
        ),
    ]
