# Generated by Django 2.2 on 2021-10-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0029_auto_20211016_0532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panelprofile',
            name='category',
        ),
        migrations.AlterField(
            model_name='outlet',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
