# Generated by Django 2.2 on 2022-01-31 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0033_auto_20220131_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='audited_data_price_max',
            field=models.DecimalField(decimal_places=2, default='10', help_text='Apply Last Month Price Cleaning on the Stores + P_Codes', max_digits=11),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='audited_data_price_min',
            field=models.DecimalField(decimal_places=2, default='-10', max_digits=11),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='audited_data_purchase_max',
            field=models.DecimalField(decimal_places=2, default='10', max_digits=11),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='audited_data_purchase_min',
            field=models.DecimalField(decimal_places=2, default='-10', max_digits=11),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='audited_data_sales_max',
            field=models.DecimalField(decimal_places=2, default='10', max_digits=11),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='audited_data_sales_min',
            field=models.DecimalField(decimal_places=2, default='-10', max_digits=11),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='audited_data_stddev',
            field=models.DecimalField(decimal_places=2, default='3', help_text='(Store + P_code Actual Sales) Shall lie in between Avg (P_code Sales) +/- 3 SD ', max_digits=11),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='audited_data_stock_max',
            field=models.DecimalField(decimal_places=2, default='10', max_digits=11),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='audited_data_stock_min',
            field=models.DecimalField(decimal_places=2, default='-10', max_digits=11),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='common_outlet_accept',
            field=models.DecimalField(decimal_places=2, default='5', help_text='ABS (Store Actual Sales /  Store Last Month Sales - 1) <= c', max_digits=11),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='common_outlet_copy',
            field=models.DecimalField(decimal_places=2, default='5', help_text='ABS (Store Actual Sales /  Store Census Sales - 1) > c', max_digits=11),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='new_outlet_accept_a',
            field=models.DecimalField(decimal_places=2, default='5', help_text='ABS (Store Actual Sales /  Store Census Sales - 1) <= a', max_digits=11),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='new_outlet_accept_b',
            field=models.DecimalField(decimal_places=2, default='5', help_text='ABS (Store Actual Sales /  Avg Cell Sales - 1) <= b', max_digits=11),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='new_outlet_drop_a',
            field=models.DecimalField(decimal_places=2, default='5', help_text='ABS (Store Actual Sales /  Store Census Sales - 1) > a', max_digits=11),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='new_outlet_drop_b',
            field=models.DecimalField(decimal_places=2, default='5', help_text='ABS (Store Actual Sales /  Avg Cell Sales - 1) > b', max_digits=11),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='weighted_cell',
            field=models.DecimalField(decimal_places=2, default='80', max_digits=11),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='weighted_store',
            field=models.DecimalField(decimal_places=2, default='80', max_digits=11),
        ),
    ]
