# Generated by Django 2.2 on 2022-01-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0034_auto_20220131_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='drop_outlet_copy_once_status',
            field=models.CharField(default='3,4', help_text='Status Code of Copy Once Dropped NC/PC  Stores - if Store is weighted Store in the MBD', max_length=250),
        ),
    ]
