# Generated by Django 2.2 on 2022-02-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0035_auto_20220131_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='import_mode',
            field=models.CharField(choices=[('APPEND', 'Append: Add records in the table.'), ('UPDATE', 'Update: If records exist update.'), ('APPENDUPDATE', 'Append/Update: If  records exist update otherwise add.'), ('REFRESH', 'Reresh: Delete all records and repopulate from the source.')], max_length=20),
        ),
    ]
