# Generated by Django 2.2 on 2022-03-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0038_auto_20220310_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdatachild',
            name='acv_pf',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='auditdatachild',
            name='num_pf',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='auditdatachild',
            name='volume',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
    ]
